# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    allow:
      - dependency-type: "direct"
    versioning-strategy: increase
    commit-message:
      prefix: "dependabot npm update"
      include: "scope"
    groups:
      development-dependencies:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
      development-dependencies-security:
        applies-to: security-updates
        dependency-type: "development"
        update-types:
          - "major"
          - "minor"
          - "patch"
      production-dependencies:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
      production-dependencies-security:
        applies-to: security-updates
        dependency-type: "production"
        update-types:
          - "major"
          - "minor"
          - "patch"
    reviewers:
      - "azurepolarbear"
      - "blwatkins"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    commit-message:
      prefix: "dependabot github-action update"
      include: "scope"
    reviewers:
      - "azurepolarbear"
      - "blwatkins"
